basepath: 'HO3D'
dataset_name: HO3D
num_frames: 2000

bottle:
    sym: -1
    num_parts: 1

box:
    sym: 3 # assymetric
    num_parts: 1

banana:
    sym: 4
    num_parts: 1

scissors:
    sym: 4
    num_parts: 1
drill:
    sym: 4
    num_parts: 1
