# dirs
experiment_dir:  2.28_hand_joint_shallow
save_dir: 10.25_HO3D_debug

# data info
no_pcld: False
points_source: pred_seg_hand
use_pred_obj_pose: False
use_pred_hand_shape: False
data_config: data_info_HO3D.yml    # name of the .yml file in data_proc
obj_category: ['bottle', 'box', 'others']
num_points: 512
tiny_val: 0

#hand config
add_points: False
input_only: hand            #['hand', 'obj', 'both']
skip_data: hand             #['hand', 'obj', 'both']
add_obj: False
gt_or_recon: gt
hand_jitter_cfg:
    mano_scale: 0
    rand_scale: 0.02        # std for 'normal' and range for 'uniform'
    rand_type: normal       #'normal' or 'uniform'
obj_jitter_cfg:
    type: normal
    s: 0
    r: 0
    t: 0

# save frequency
freq:
    save: 5

# network options
track: hand   #['hand', 'obj', 'both', False]
pointnet_cfg:
    camera: pointnet2_camera_shallow1.yml

network:
    learnable_embedding: False
    type: handbase
    nore: False
    global_pose: pred
    use_opt_joint: False
    handframe: kp
    backbone_out_dim: 384
    mlp: small
    notrans: False
    attn: False
    vis_thre: 0.02
    use_optimization: False
    particle_size: 5120
    iterations: 5
    use_sdf: False
    sdf_code_source: gt
    use_gt_latent_code: False
    NetworkSpecs:
        dims: [ 512, 512, 512, 512, 512, 512, 512, 512 ]
        dropout : [0, 1, 2, 3, 4, 5, 6, 7]
        dropout_prob : 0.2
        norm_layers : [0, 1, 2, 3, 4, 5, 6, 7]
        latent_in : [4]
        xyz_in_all : False
        use_tanh : False
        latent_dropout : False
        weight_norm : True
    
# loss weights
loss_weight:
    penetrate_sum_loss: 10
    sil_loss: 10
    attraction_loss: 5
    vis_regu_loss: 10
    invis_regu_loss: 0
    temporal_smooth: 1

# optimization options
optimizer: Adam
weight_decay: 0.0001
warm_up: 0
learning_rate: 0.0001
lr_policy: step
lr_gamma: 0.5 # lr decay rate
lr_step_size: 20
lr_clip: 0.00001 # min lr

# bn momentum adjustment
momentum_original: 0.1
momentum_decay: 0.5
momentum_step_size: 20  # = lr_step_size
momentum_min: 0.01

# training options
weight_init: xavier
batch_size: 1
total_epoch: 300


# device
cuda_id: 0


