# dirs
experiment_dir: 3.7_final_obj_bottle_test_HOI4D
save_dir: 3.7_final_obj_bottle_test_HOI4D

# data info
points_source: pred_seg_obj
use_pred_obj_pose: False
no_pcld: False
data_config: data_info_HOI4D.yml    # name of the .yml file in data_proc
obj_category: 'bottle'
num_points: 1024
tiny_val: 50

#hand config
input_only: obj            #['hand', 'obj', 'both']
skip_data: obj             #['hand', 'obj', 'both']
add_obj: False
gt_or_recon: gt
hand_jitter_cfg:
    mano_scale: 0
    rand_scale: 0.01        # std for 'normal' and range for 'uniform'
    rand_type: normal       #'normal' or 'uniform'
obj_jitter_cfg:
    type: normal
    s: 0
    r: 5
    t: 0.03

# save frequency
freq:
    save: 5

# network options
track: obj_opt   #['hand', 'obj', 'both', False]
pointnet_cfg:
    camera: pointnet2_camera.yml
network:
    type: obj_optimization
    sdf_code_source: sdf_on_pred_seg
    use_gt_latent_code: False
    NetworkSpecs:
        dims: [ 512, 512, 512, 512, 512, 512, 512, 512 ]
        dropout : [0, 1, 2, 3, 4, 5, 6, 7]
        dropout_prob : 0.2
        norm_layers : [0, 1, 2, 3, 4, 5, 6, 7]
        latent_in : [4]
        xyz_in_all : False
        use_tanh : False
        latent_dropout : False
        weight_norm : True
optimization:
    silhouette: False
    sdf_weight: 500
    vt_weight: 0
    vr_weight: 0
    at_weight: 0
    ar_weight: 0
    scaling_coefficient2: 0.5

# loss weights
loss_weight:
    nocs_dist_loss: 1
    nocs_pwm_loss: 1
    nocs_loss: 1
    seg_loss: 1
    rloss: 1
    tloss: 1
    sloss: 1

pose_loss_type:
    r: raw_3d
    s: l1
    t: l1
    point: l1

# optimization options
optimizer: Adam
weight_decay: 0.0001
warm_up: 0
learning_rate: 0.001
lr_policy: step
lr_gamma: 0.5 # lr decay rate
lr_step_size: 20
lr_clip: 0.00001 # min lr

# bn momentum adjustment
momentum_original: 0.1
momentum_decay: 0.5
momentum_step_size: 20  # = lr_step_size
momentum_min: 0.01

# training options
weight_init: xavier
batch_size: 1
total_epoch: 250


# device
cuda_id: 0


