# dirs
experiment_dir: 10.25_debug
resume_epoch: -1

# data info
use_pred_obj_pose: False
use_pred_hand_shape: False
data_config: data_info_newShapeNet.yml    # name of the .yml file in data_proc
obj_category: ['bottle_sim', 'car_sim', 'bowl_sim']
num_points: 512
tiny_val: 0

#hand config
input_only: hand            #['hand', 'obj', 'both']
skip_data: hand             #['hand', 'obj', 'both']
add_obj: False
gt_or_recon: gt
hand_jitter_cfg:
    mano_scale: 0
    rand_scale: 0.02        # std for 'normal' and range for 'uniform'
    rand_type: normal       #'normal' or 'uniform'
    jitter_shape: False
    jitter_by_MANO: False

obj_jitter_cfg:
    type: normal
    s: 0
    r: 0
    t: 0

# save frequency
freq:
    save: 5

# network options
track: False   #['hand', 'obj', 'both', False]
pointnet_cfg:
    camera: pointnet2_camera_shallow1.yml
network:
    type: handbase
    handframe: kp
    nore: False
    backbone_out_dim: 384
    mlp: small
    notrans: False
    attn: False
    vis_thre: 0.02
    use_optimization: False
    global_pose: pred
# loss weights
loss_weight:
    hand_pred_kp_loss: 10
    hand_pred_r_loss: 1
    hand_pred_t_loss: 1

# optimization options
optimizer: Adam
weight_decay: 0.0001
warm_up: 0
learning_rate: 0.0001
lr_policy: step
lr_gamma: 0.5 # lr decay rate
lr_step_size: 20
lr_clip: 0.00001 # min lr

# bn momentum adjustment
momentum_original: 0.1
momentum_decay: 0.5
momentum_step_size: 20  # = lr_step_size
momentum_min: 0.01

# training options
weight_init: xavier
batch_size: 32
total_epoch: 300


# device
cuda_id: 0


